export type ReadingEntry = {
  year: string;
  authors: string;
  title: string;
  publication: string;
  links: readonly {
    label: string;
    href: string;
  }[];
};

type LinkSeed = readonly [label: string, href: string];

const entry = (
  year: string,
  authors: string,
  title: string,
  publication: string,
  links: readonly LinkSeed[] = [],
): ReadingEntry => ({
  year,
  authors,
  title,
  publication,
  links: links.map(([label, href]) => ({ label, href })),
});

export const readingList: readonly ReadingEntry[] = [
  entry(
    "1977",
    "S. Bloch",
    "Algebraic K-Theory and Crystalline Cohomology",
    "Publ. Math. IHÉS 47, 187–268",
    [["Numdam", "https://www.numdam.org/item/PMIHES_1977__47__187_0/"]],
  ),
  entry(
    "1979",
    "L. Illusie",
    "Complexe de de Rham–Witt",
    "Astérisque 63, 83–112",
    [["Numdam", "https://archive.numdam.org/item/AST_1979__63__83_0/"]],
  ),
  entry(
    "1979",
    "L. Illusie",
    "Complexe de de Rham–Witt et cohomologie cristalline",
    "Ann. Sci. Éc. Norm. Supér. (4) 12, 501–661",
    [
      ["Numdam", "https://www.numdam.org/item/ASENS_1979_4_12_4_501_0/"],
      [
        "errata",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Errdrw2.pdf",
      ],
    ],
  ),
  entry(
    "1979",
    "M. Raynaud",
    "p-Torsion du schéma de Picard",
    "Astérisque 64, 87–148",
    [["Numdam", "https://www.numdam.org/item/AST_1979__64__87_0/"]],
  ),
  entry(
    "1980",
    "N. O. Nygaard",
    "Higher de Rham–Witt Complexes of Supersingular K3 Surfaces",
    "Compositio Math. 42, 245–271",
    [["Numdam", "https://www.numdam.org/item/CM_1980__42_2_245_0/"]],
  ),
  entry(
    "1981",
    "N. O. Nygaard",
    "Slopes of Powers of Frobenius on Crystalline Cohomology",
    "Ann. Sci. Éc. Norm. Supér. (4) 14, 369–401",
    [["DOI", "https://doi.org/10.24033/asens.1411"]],
  ),
  entry(
    "1983",
    "L. Illusie and M. Raynaud",
    "Les suites spectrales associées au complexe de de Rham–Witt",
    "Publ. Math. IHÉS 57, 73–212",
    [["Numdam", "https://www.numdam.org/item/PMIHES_1983__57__73_0/"]],
  ),
  entry(
    "1983",
    "L. Illusie",
    "Finiteness, Duality, and Künneth Theorems in the Cohomology of the de Rham–Witt Complex",
    "Lecture Notes in Math. 1016, 20–72",
    [["DOI", "https://doi.org/10.1007/BFb0099957"]],
  ),
  entry(
    "1984",
    "T. Ekedahl",
    "On the Multiplicative Properties of the de Rham–Witt Complex. I",
    "Ark. Mat. 22, 185–239",
    [["DOI", "https://doi.org/10.1007/BF02384380"]],
  ),
  entry(
    "1984",
    "T. Zink",
    "Cartier Theory of Commutative Formal Groups",
    "Teubner-Texte zur Mathematik 68",
    [
      [
        "English translation",
        "https://perso.univ-rennes1.fr/matthieu.romagny/articles/Zink_Cartier_theory_of_commutative_formal_groups.pdf",
      ],
    ],
  ),
  entry(
    "1985",
    "T. Ekedahl",
    "On the Multiplicative Properties of the de Rham–Witt Complex. II",
    "Ark. Mat. 23, 53–102",
    [["DOI", "https://doi.org/10.1007/BF02384419"]],
  ),
  entry(
    "1985",
    "R. Crew",
    "On Torsion in the Slope Spectral Sequence",
    "Compositio Math. 56, 79–86",
    [["Numdam", "https://www.numdam.org/item/CM_1985__56_1_79_0/"]],
  ),
  entry(
    "1985",
    "M. Gros",
    "Classes de Chern et classes de cycles en cohomologie de Hodge–Witt logarithmique",
    "Mém. Soc. Math. France (N.S.) 21, 1–87",
    [["DOI", "https://doi.org/10.24033/msmf.322"]],
  ),
  entry(
    "1986",
    "T. Ekedahl",
    "Diagonal Complexes and F-Gauge Structures",
    "Travaux en Cours 18, Hermann, 120 pp.",
    [
      [
        "record",
        "https://search.worldcat.org/title/Diagonal-complexes-and-F-gauge-structures/oclc/15263713",
      ],
    ],
  ),
  entry(
    "1986",
    "S. Bloch and K. Kato",
    "p-Adic Étale Cohomology",
    "Publ. Math. IHÉS 63, 107–152",
    [["Numdam", "https://www.numdam.org/item/PMIHES_1986__63__107_0/"]],
  ),
  entry(
    "1986",
    "J. S. Milne",
    "Values of Zeta Functions of Varieties over Finite Fields",
    "Amer. J. Math. 108, 297–360",
    [
      ["PDF", "https://www.jmilne.org/math/articles/1986a.pdf"],
      ["addendum", "https://www.jmilne.org/math/articles/add/1986a.pdf"],
    ],
  ),
  entry(
    "1988",
    "J.-Y. Étesse",
    "Complexe de de Rham–Witt à coefficients dans un cristal",
    "Compositio Math. 66, 57–120",
    [["Numdam", "https://www.numdam.org/item/CM_1988__66_1_57_0/"]],
  ),
  entry(
    "1990",
    "L. Illusie",
    "Ordinarité des intersections complètes générales",
    "The Grothendieck Festschrift II, Progr. Math. 87, 376–405",
  ),
  entry(
    "1991",
    "O. Hyodo",
    "On the de Rham–Witt Complex Attached to a Semi-Stable Family",
    "Compositio Math. 78, 241–260",
    [["Numdam", "https://www.numdam.org/item/CM_1991__78_3_241_0/"]],
  ),
  entry(
    "1993",
    "A. Mokrane",
    "La suite spectrale des poids en cohomologie de Hyodo–Kato",
    "Duke Math. J. 72, 301–337",
    [["DOI", "https://doi.org/10.1215/S0012-7094-93-07211-0"]],
  ),
  entry(
    "1994",
    "O. Hyodo and K. Kato",
    "Semi-Stable Reduction and Crystalline Cohomology with Logarithmic Poles",
    "Astérisque 223, 221–268",
    [["Numdam", "https://www.numdam.org/item/AST_1994__223__221_0/"]],
  ),
  entry(
    "1994",
    "L. Illusie",
    "Réduction semi-stable ordinaire, cohomologie étale p-adique et cohomologie de de Rham",
    "Astérisque 223, 209–220",
    [["Numdam", "https://numdam.org/item/AST_1994__223__209_0/"]],
  ),
  entry(
    "1996",
    "L. Hesselholt",
    "On the p-Typical Curves in Quillen’s K-Theory",
    "Acta Math. 177, 1–53",
    [["DOI", "https://doi.org/10.1007/BF02392597"]],
  ),
  entry(
    "1999",
    "T. Geisser and L. Hesselholt",
    "Topological Cyclic Homology of Schemes",
    "Proc. Sympos. Pure Math. 67, 41–87",
    [["author page", "https://web.math.ku.dk/~trk734/papers/008/"]],
  ),
  entry(
    "2003",
    "L. Hesselholt and I. Madsen",
    "On the K-Theory of Local Fields",
    "Ann. of Math. (2) 158, 1–113",
    [["DOI", "https://doi.org/10.4007/annals.2003.158.1"]],
  ),
  entry(
    "2004",
    "S. Bloch",
    "Crystals and de Rham–Witt Connections",
    "J. Inst. Math. Jussieu 3, 315–326",
    [["DOI", "https://doi.org/10.1017/S147474800400009X"]],
  ),
  entry(
    "2004",
    "A. Langer and T. Zink",
    "De Rham–Witt Cohomology for a Proper and Smooth Morphism",
    "J. Inst. Math. Jussieu 3, 231–314",
    [["PDF", "https://www.math.uni-bielefeld.de/~zink/dRW.pdf"]],
  ),
  entry(
    "2004",
    "L. Hesselholt and I. Madsen",
    "On the de Rham–Witt Complex in Mixed Characteristic",
    "Ann. Sci. Éc. Norm. Supér. (4) 37, 1–43",
    [["DOI", "https://doi.org/10.1016/j.ansens.2003.06.001"]],
  ),
  entry(
    "2004",
    "K. Joshi",
    "A p-Adic Proof of Hodge Symmetry for Threefolds",
    "C. R. Acad. Sci. Paris, Ser. I 338, 781–786",
    [
      ["DOI", "https://doi.org/10.1016/j.crma.2003.11.038"],
      ["arXiv", "https://arxiv.org/abs/math/0110066"],
    ],
  ),
  entry(
    "2005",
    "L. Hesselholt",
    "The Absolute and Relative de Rham–Witt Complexes",
    "Compositio Math. 141, 1109–1127",
    [["DOI", "https://doi.org/10.1112/S0010437X05001442"]],
  ),
  entry(
    "2005",
    "J. S. Milne and N. Ramachandran",
    "The de Rham–Witt and Zₚ-Cohomologies of an Algebraic Variety",
    "Adv. Math. 198, 36–42",
    [["arXiv", "https://arxiv.org/abs/math/0501380"]],
  ),
  entry(
    "2005",
    "A. Langer and T. Zink",
    "Gauss–Manin Connection via Witt-Differentials",
    "Nagoya Math. J. 179, 1–16",
    [["DOI", "https://doi.org/10.1017/S0027763000025587"]],
  ),
  entry(
    "2005",
    "N. Ramachandran",
    "Values of Zeta Functions at s = 1/2",
    "Int. Math. Res. Not. 2005, 1519–1541",
    [["arXiv", "https://arxiv.org/abs/math/0502507"]],
  ),
  entry(
    "2006",
    "T. Geisser and L. Hesselholt",
    "The de Rham–Witt Complex and p-Adic Vanishing Cycles",
    "J. Amer. Math. Soc. 19, 1–36",
    [["DOI", "https://doi.org/10.1090/S0894-0347-05-00505-9"]],
  ),
  entry(
    "2007",
    "P. Berthelot, S. Bloch, and H. Esnault",
    "On Witt Vector Cohomology for Singular Varieties",
    "Compositio Math. 143, 363–392",
    [["DOI", "https://doi.org/10.1112/S0010437X06002533"]],
  ),
  entry(
    "2009",
    "L. Illusie",
    "Review of de Rham–Witt Theory",
    "Loen lecture notes, 77 pp.",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/illusie_loen.pdf",
      ],
    ],
  ),
  entry(
    "2011",
    "C. Davis, A. Langer, and T. Zink",
    "Overconvergent de Rham–Witt Cohomology",
    "Ann. Sci. Éc. Norm. Supér. (4) 44, 197–262",
    [["DOI", "https://doi.org/10.24033/asens.2143"]],
  ),
  entry(
    "2011",
    "L. Illusie",
    "De Rham–Witt Complexes and p-Adic Hodge Theory",
    "Sapporo seminar pre-notes",
    [
      [
        "notes",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Illusie-Sapporo1a.pdf",
      ],
      [
        "log / Hyodo–Kato",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Illusie-Sapporo-Hyodo-Kato.pdf",
      ],
    ],
  ),
  entry(
    "2015",
    "J. S. Milne and N. Ramachandran",
    "The p-Cohomology of Algebraic Varieties and Special Values of Zeta Functions",
    "J. Inst. Math. Jussieu 14, 801–835",
    [["arXiv", "https://arxiv.org/abs/1310.4469"]],
  ),
  entry(
    "2018",
    "B. Bhatt, M. Morrow, and P. Scholze",
    "Integral p-Adic Hodge Theory",
    "Publ. Math. IHÉS 128, 219–397",
    [["arXiv", "https://arxiv.org/abs/1602.03148"]],
  ),
  entry(
    "2018",
    "T. Nikolaus and P. Scholze",
    "On Topological Cyclic Homology",
    "Acta Math. 221, 203–409",
    [["DOI", "https://doi.org/10.4310/ACTA.2018.v221.n2.a1"]],
  ),
  entry(
    "2018",
    "L. Hesselholt",
    "Topological Hochschild Homology and the Hasse–Weil Zeta Function",
    "Contemp. Math. 708, 157–180",
    [["arXiv", "https://arxiv.org/abs/1602.01980"]],
  ),
  entry(
    "2019",
    "B. Bhatt, M. Morrow, and P. Scholze",
    "Topological Hochschild Homology and Integral p-Adic Hodge Theory",
    "Publ. Math. IHÉS 129, 199–310",
    [["arXiv", "https://arxiv.org/abs/1802.03261"]],
  ),
  entry(
    "2019",
    "L. Illusie",
    "p-Adic Cohomologies: History, and New Developments",
    "Landau lecture slides",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Landau1.pdf",
      ],
    ],
  ),
  entry(
    "2020",
    "S. Molokov",
    "Prismatic Cohomology and de Rham–Witt Forms",
    "arXiv:2008.04956v3; to appear in Sbornik: Mathematics",
    [["arXiv", "https://arxiv.org/abs/2008.04956"]],
  ),
  entry(
    "2020",
    "L. Illusie",
    "Partial Degeneration of Hodge to de Rham Spectral Sequences and Kodaira Type Vanishing Theorems for Locally Complete Intersections in Positive Characteristic",
    "preprint",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/DI-revisited2.pdf",
      ],
    ],
  ),
  entry(
    "2020",
    "K. Joshi",
    "Crystalline Aspects of Geography of Low Dimensional Varieties I: Numerology",
    "European J. Math. 6, 1111–1175",
    [
      ["DOI", "https://doi.org/10.1007/s40879-020-00416-x"],
      ["arXiv", "https://arxiv.org/abs/1403.6402"],
    ],
  ),
  entry(
    "2021",
    "B. Bhatt, J. Lurie, and A. Mathew",
    "Revisiting the de Rham–Witt Complex",
    "Astérisque 424, viii+158 pp.",
    [["arXiv", "https://arxiv.org/abs/1805.05501"]],
  ),
  entry(
    "2021",
    "B. Antieau and T. Nikolaus",
    "Cartier Modules and Cyclotomic Spectra",
    "J. Amer. Math. Soc. 34, 1–78",
    [["DOI", "https://doi.org/10.1090/jams/951"]],
  ),
  entry(
    "2021",
    "S. Mondal",
    "Dieudonné Theory via Cohomology of Classifying Stacks",
    "Forum Math. Sigma 9, e81",
    [["arXiv", "https://arxiv.org/abs/2002.05413"]],
  ),
  entry(
    "2021",
    "L. Illusie",
    "A New Approach to de Rham–Witt Complexes, after Bhatt, Lurie, and Mathew",
    "Rend. Sem. Mat. Univ. Padova 146, 177–221",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Illusie-BLM6.pdf",
      ],
    ],
  ),
  entry(
    "2022",
    "B. Bhatt and J. Lurie",
    "Absolute Prismatic Cohomology",
    "preprint, 242 pp.",
    [["arXiv", "https://arxiv.org/abs/2201.06120"]],
  ),
  entry(
    "2022",
    "B. Bhatt and J. Lurie",
    "The Prismatization of p-Adic Formal Schemes",
    "preliminary version",
    [["arXiv", "https://arxiv.org/abs/2201.06124"]],
  ),
  entry(
    "2022",
    "S. Mondal",
    "Gₐᵖᵉʳᶠ-Modules and de Rham Cohomology",
    "Adv. Math. 409, 108691",
    [["arXiv", "https://arxiv.org/abs/2101.03146"]],
  ),
  entry(
    "2022",
    "S. Mondal",
    "Reconstruction of the Stacky Approach to de Rham Cohomology",
    "Math. Z. 302, 687–693",
    [["arXiv", "https://arxiv.org/abs/2202.07089"]],
  ),
  entry(
    "2022",
    "S. Mondal",
    "A Computation of Prismatic Dieudonné Module",
    "Acta Arith. 205, 87–96",
    [
      [
        "PDF",
        "https://www.math.purdue.edu/~mondalsh/papers/A-computation-of-prismatic-Dieudonne-module.pdf",
      ],
    ],
  ),
  entry(
    "2022",
    "L. Illusie",
    "New Perspectives on de Rham Cohomology, after Bhatt–Lurie, Drinfeld, et al.",
    "lecture slides",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/DI-slides-new1.pdf",
      ],
    ],
  ),
  entry(
    "2022",
    "L. Illusie",
    "New Advances on de Rham Cohomology in Positive or Mixed Characteristic, after Bhatt–Lurie, Drinfeld, and Petrov",
    "lecture slides",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Bruno60-slides.pdf",
      ],
    ],
  ),
  entry(
    "2022",
    "L. Illusie",
    "Lectures on the de Rham Complex",
    "Daniel Kan Lectures",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Kan-Lectures-Illusie-A.pdf",
      ],
    ],
  ),
  entry(
    "2022",
    "B. Antieau and D. Bragg",
    "Derived Invariants from Topological Hochschild Homology",
    "Algebraic Geometry 9, 364–399",
    [["arXiv", "https://arxiv.org/abs/1906.12267"]],
  ),
  entry(
    "2022",
    "A. Mathew",
    "Some Recent Advances in Topological Hochschild Homology",
    "Bull. Lond. Math. Soc. 54, 1–44",
    [["arXiv", "https://arxiv.org/abs/2101.00668"]],
  ),
  entry(
    "2022",
    "Y. Nakkajima",
    "Artin–Mazur Heights and Yobuko Heights of Proper Log Smooth Schemes of Cartier Type, and Hodge–Witt Decompositions and Chow Groups of Quasi-F-Split Threefolds",
    "J. Reine Angew. Math. 787, 1–44",
    [["arXiv", "https://arxiv.org/abs/1902.00185"]],
  ),
  entry(
    "2023",
    "B. Bhatt",
    "Prismatic F-Gauges",
    "Princeton Math 549 lecture notes",
    [
      [
        "course",
        "https://www.math.ias.edu/~bhatt/teaching/mat549f22/",
      ],
      [
        "PDF",
        "https://www.math.ias.edu/~bhatt/teaching/mat549f22/lectures.pdf",
      ],
    ],
  ),
  entry(
    "2023",
    "F. Yobuko",
    "Quasi-F-Split and Hodge–Witt",
    "arXiv:2312.00682v1",
    [["arXiv", "https://arxiv.org/abs/2312.00682"]],
  ),
  entry(
    "2024",
    "V. Drinfeld",
    "Prismatization",
    "Selecta Math. (N.S.) 30, Paper 49",
    [["arXiv", "https://arxiv.org/abs/2005.04746"]],
  ),
  entry(
    "2024",
    "J. McCandless",
    "On Curves in K-Theory and TR",
    "J. Eur. Math. Soc. 26, 4315–4373",
    [["arXiv", "https://arxiv.org/abs/2102.08281"]],
  ),
  entry(
    "2024",
    "Z. Mao",
    "Noncommutative Relative de Rham–Witt Complex via the Norm",
    "arXiv:2410.05998v1",
    [["arXiv", "https://arxiv.org/abs/2410.05998"]],
  ),
  entry(
    "2024",
    "K. Bals",
    "The Topological Cartier–Raynaud Ring",
    "arXiv:2404.10724v1",
    [["arXiv", "https://arxiv.org/abs/2404.10724"]],
  ),
  entry(
    "2024",
    "F. Andriopoulos",
    "TR and the r-Nygaard Filtered Prismatic Cohomology",
    "arXiv:2412.00914v2",
    [["arXiv", "https://arxiv.org/abs/2412.00914"]],
  ),
  entry(
    "2024",
    "F. Andriopoulos",
    "TR with Logarithmic Poles and the de Rham–Witt Complex",
    "arXiv:2412.00929v1",
    [["arXiv", "https://arxiv.org/abs/2412.00929"]],
  ),
  entry(
    "2024",
    "K. Magidson",
    "Witt Vectors and δ-Cartier Rings",
    "arXiv:2409.03877v4",
    [["arXiv", "https://arxiv.org/abs/2409.03877"]],
  ),
  entry(
    "2024",
    "R. Fernando",
    "Saturated de Rham–Witt Complexes with Unit-Root Coefficients",
    "arXiv:2406.02922v2",
    [["arXiv", "https://arxiv.org/abs/2406.02922"]],
  ),
  entry(
    "2025",
    "N. Riggenbach",
    "K-Theory of Truncated Polynomials",
    "Math. Z. 310, Article 59",
    [["arXiv", "https://arxiv.org/abs/2211.11110"]],
  ),
  entry(
    "2025",
    "M. Darrell and N. Riggenbach",
    "TR of Quasiregular Semiperfect Rings Is Even",
    "Selecta Math. (N.S.) 31, Article 63",
    [["arXiv", "https://arxiv.org/abs/2308.13008"]],
  ),
  entry(
    "2025",
    "S. K. Devalapurkar and S. Mondal",
    "p-Typical Curves on p-Adic Tate Twists and de Rham–Witt Forms",
    "Adv. Math. 479, 110448",
    [["arXiv", "https://arxiv.org/abs/2309.16623"]],
  ),
  entry(
    "2025",
    "E. Dotto",
    "An Analogue of the Milnor Conjecture for the de Rham–Witt Complex in Characteristic 2",
    "Forum Math. Sigma 13, e87",
    [["arXiv", "https://arxiv.org/abs/2405.02054"]],
  ),
  entry(
    "2025",
    "E. Dotto, A. Krause, T. Nikolaus, and I. Patchkoria",
    "Witt Vectors with Coefficients and TR",
    "Proc. Lond. Math. Soc. (3) 130, e70047",
    [["arXiv", "https://arxiv.org/abs/2312.12971"]],
  ),
  entry(
    "2025",
    "S. Mondal",
    "Dieudonné Theory via Classifying Stacks and Prismatic F-Gauges",
    "arXiv:2405.12967v3; to appear in Cambridge J. Math.",
    [["arXiv", "https://arxiv.org/abs/2405.12967"]],
  ),
  entry(
    "2025",
    "S. Mondal",
    "Zeta Function of F-Gauges and Special Values",
    "arXiv:2501.05027v1",
    [["arXiv", "https://arxiv.org/abs/2501.05027"]],
  ),
  entry(
    "2025",
    "L. Grammatica, A. N. Skorobogatov, and Y. Yang",
    "Brauer Groups of Abelian Varieties over Fields of Finite Characteristic",
    "arXiv:2511.08840v2",
    [["arXiv", "https://arxiv.org/abs/2511.08840"]],
  ),
  entry(
    "2025",
    "A. N. Skorobogatov",
    "Boundedness of the p-Primary Torsion of the Brauer Group of Products of Varieties",
    "Forum Math. Sigma 13, e134",
    [["arXiv", "https://arxiv.org/abs/2404.19150"]],
  ),
  entry(
    "2025",
    "S. Mondal, T. Moulinos, and L. Yang",
    "Artin–Mazur Formal Groups and Milne Duality via Unipotent Spectra",
    "arXiv:2510.06152v1",
    [
      ["arXiv", "https://arxiv.org/abs/2510.06152"],
      [
        "PDF",
        "https://www.math.purdue.edu/~mondalsh/papers/Unipotentspectra.pdf",
      ],
    ],
  ),
  entry(
    "2025",
    "F. Wagner",
    "q-Witt Vectors and q-Hodge Complexes",
    "arXiv:2410.23078v5",
    [["arXiv", "https://arxiv.org/abs/2410.23078"]],
  ),
  entry(
    "2025",
    "R. Fernando",
    "Dimensional Vanishing of the Saturated de Rham–Witt Complex",
    "arXiv:2507.22314v2",
    [["arXiv", "https://arxiv.org/abs/2507.22314"]],
  ),
  entry(
    "2026",
    "S. Mondal and E. Reinecke",
    "Unipotent Homotopy Theory of Schemes",
    "J. Amer. Math. Soc. 39, 205–312",
    [["arXiv", "https://arxiv.org/abs/2302.10703"]],
  ),
  entry(
    "2026",
    "Y. Yang",
    "Remarks on p-Primary Torsion of the Brauer Group",
    "J. Number Theory 279, 184–215",
    [
      ["DOI", "https://doi.org/10.1016/j.jnt.2025.06.003"],
      ["arXiv v2", "https://arxiv.org/abs/2410.09969v2"],
    ],
  ),
  entry(
    "2026",
    "S. Li and Y. Yang",
    "On de Rham–Witt Cohomology of Classifying Stacks",
    "arXiv:2604.03062v1",
    [["arXiv", "https://arxiv.org/abs/2604.03062"]],
  ),
  entry(
    "2026",
    "S. Mondal",
    "Syntomic Cohomology of Rational Weights and Zeta Functions",
    "author manuscript",
    [
      [
        "PDF",
        "https://www.math.purdue.edu/~mondalsh/papers/Syntomic-cohomology-of-rational-weights.pdf",
      ],
    ],
  ),
  entry(
    "2026",
    "L. Illusie",
    "Recent Developments on Zeta Values over Finite Fields, after S. Mondal",
    "author manuscript, 52 pp.",
    [
      [
        "PDF",
        "https://www.imo.universite-paris-saclay.fr/~luc.illusie/Illusie-zeta-values-Mondal.pdf",
      ],
    ],
  ),
  entry(
    "2026",
    "B. Bhatt, A. Mathew, and V. Vologodsky",
    "Sheared Witt Vectors",
    "arXiv:2607.01178v1",
    [["arXiv", "https://arxiv.org/abs/2607.01178"]],
  ),
  entry(
    "2026",
    "S. Mondal and M. Olsson",
    "Height 1 Group Schemes and Prismatic F-Gauges",
    "arXiv:2604.16066v1",
    [["arXiv", "https://arxiv.org/abs/2604.16066"]],
  ),
  entry(
    "2026",
    "Y. Zhang",
    "Higher Dimensional Dominoes in de Rham–Witt Cohomology",
    "arXiv:2607.26323v1",
    [["arXiv", "https://arxiv.org/abs/2607.26323"]],
  ),
];
